site_name: Mad Migration
site_url: 
site_description: Mad Migration tool documention easy and fast migration
dev_addr: 127.0.0.1:8080
authors:
    - Hasan Aliyev
    - Tural Muradov
    - Sabuhi Shukurov
theme:
  name: material

  palette:
    scheme: slate
    primary: blue grey
    accent: cyan
    
  font:
    text: Roboto
    
  features:
    - search.highlight
    

  icon:
    repo: fontawesome/brands/github
  logo: img/madmigration.jpg
repo_name: mad-migration
repo_url: https://github.com/MadMigrationTeam/mad-migration
edit_uri: ''

plugins:
- search
- markdownextradata:
    data: data

markdown_extensions:
  - toc:
      permalink: true

      
nav:
  - Mad Migration: index.md
  - Install: install.md
  - Getting Started: getting-started.md
  - Full Example: example.md
  - License: license.md


