site_name: Mad Migration
site_url: 
site_description: Mad Migration tool documention easy and fast migration

repo_name: aliyevh/mad-migration
repo_url: https://github.com/AliyevH/mad-migration
edit_uri: ''

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: cyan
  font:
    text: Roboto
  features:
    - search.highlight
  icon:
    repo: fontawesome/brands/github



plugins:
- search
- markdownextradata:
    data: data

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Mad Migration: index.md
  - Installation: install.md
  - Getting Started: getting-started.md
  - Full Example: example.md
  - License: license.md
